### ISSUE TITLE
[Feature Request] Integration with GPIO on RPI

### ISSUE THREAD

**Issue by JiroMusik** [mathewmeconry/MMM-HomeAssistant-Touch#8]
Hi there,
I love using your Module on my mirrors - they are looking great and working fine - but since I got a 21" mirror, and no touchscreen - but touch buttons and sliders - I would love to integrate them. They are all Digital so they can be intrgrated directly (not like GPIO Module with analog inputs via arduino -> PI).

Let me know if you could imagine implementing this or guide me on that way.

all the best
jiromusik

**Comment by mathewmeconry** [comment]
Hey
Unfortunately, I don't have any experience with GPIO on RPI and no hardware to test anything.
But if you want to do it on your own here are some ways I could imagine how it could work:

**Option 1**
Integrate the GPIO stuff directly into the module by extending the `node_helper.js` file. I don't think this is a good idea because this would open up a box of worms for all the different types of buttons and so on.
The supported functionality you can find here:
https://github.com/mathewmeconry/MMM-HomeAssistant-Touch/blob/80f96976ee960ccf8535e6034b13eb4c815623ec/node_helper.js#L35-L71

**Option 2**
Write a module that handles your particular model of inputs. I assume not every touch button revision is the same so I think this is the better approach.
Then send a `CONNECT` event with the connection details (access token, URL, etc) to the module. You can get the module with the helpers provided by MM2 (https://docs.magicmirror.builders/development/helper-methods.html#module-selection).
Because all the modules of the same type share the backend it doesn't matter which one you select.
After sending the `CONNECT` event the module backend establishes a connection to HA for you and informs you about updates on the entities you listen to via the `CHANGED_STATE` event.
After `CONNECT` you can also send other events as described here
https://github.com/mathewmeconry/MMM-HomeAssistant-Touch/blob/80f96976ee960ccf8535e6034b13eb4c815623ec/node_helper.js#L35-L71

**Comment by mathewmeconry** [comment]
Closing for housekeeping
